services:

  krakend:
    image: devopsfaith/krakend:latest
    depends_on:
      - accounts
      - blogs
    ports:
      - 8080:8080
    volumes:
      - ./krakend.json:/etc/krakend/krakend.json
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/__health" ]
      interval: 30s
      timeout: 10s
      retries: 5

  accounts:
    image: ktor-accounts
    build: accounts
    depends_on:
      mongo-accounts:
        condition: service_healthy
    ports:
      - 8081:8080
    environment:
      - CONNECTION_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo-blogs:27017/?authSource=admin
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 10s
      timeout: 10s
      retries: 5
  mongo-accounts:
    image: mongo:latest
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongosh admin -u ${MONGO_INITDB_ROOT_USERNAME} -p ${MONGO_INITDB_ROOT_PASSWORD} --quiet | grep 1
      interval: 10s
      timeout: 10s
      retries: 5
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD

  blogs:
    image: ktor-blogs
    build: blogs
    depends_on:
      mongo-blogs:
        condition: service_healthy
    ports:
      - 8082:8080
    environment:
      - CONNECTION_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo-blogs:27017/?authSource=admin
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 10s
      timeout: 10s
      retries: 5
  mongo-blogs:
    image: mongo:latest
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongosh admin -u ${MONGO_INITDB_ROOT_USERNAME} -p ${MONGO_INITDB_ROOT_PASSWORD} --quiet | grep 1
      interval: 10s
      timeout: 10s
      retries: 5
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
